### ISSUE TITLE
Version 1.6.1(1821)에서 XUnity.AutoTranslator 포함 시, 게임이 튕기는 문제

### ISSUE THREAD

**Issue by StarlightPN** [StarlightPN/A25-KoreanPatch#1]
BepInEx 단독으로는 문제 없이 실행 가능합니다.
XUnity.AutoTranslator 5.3.0 플러그인 포함 시, 실행 직후 게임이 강제 종료됩니다.

XUnity.AutoTranslator의 신규 버전이 나오거나, 게임 클라이언트 업데이트를 통해 해당 문제가 해결될 경우 다시 진행합니다.

BepInEx의 로그는 아래와 같습니다.

[Message: Preloader] BepInEx 6.0.0-be.672 - AtelierResleriana
[Message: Preloader] Built from commit 472e950179f4a5ab2e4a89f26dba793795fb6811
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2021.3.23f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7
[Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Warning:Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
[Info   :Il2CppInterop] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[Info   :   BepInEx] 2 plugins to load
[Info   :   BepInEx] Loading [XUnity Auto Translator 5.3.0]
[Info   :Il2CppInterop] Registered mono type XUnity.AutoTranslator.Plugin.Core.PluginLoader+AutoTranslatorProxyBehaviour in il2cpp domain
[Info   :   BepInEx] Loading [XUnity Resource Redirector 2.1.0]
[Message:   BepInEx] Chainloader startup complete
[Info   :XUnity.AutoTranslator] Force loading ALL proxy assemblies.
[Warning:XUnity.AutoTranslator] Could not find 'UnityEngine.TextMesh' in IL2CPP domain even though it could be found in the managed domain.
[Warning:XUnity.AutoTranslator] Could not find 'UnityEngine.WWW' in IL2CPP domain even though it could be found in the managed domain.
[Warning:XUnity.AutoTranslator] Could not find 'UnityEngine.GUI+ToolbarButtonSize' in IL2CPP domain even though it could be found in the managed domain.
[Info   :XUnity.AutoTranslator] Version of TextMesh Pro: 1.4.0.
[Warning:  HarmonyX] AccessTools.Method: Could not find method for type TMPro.TMP_Text and name SetCharArray and parameters (Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppStructArray<int>, int, int)
[Warning:XUnity.AutoTranslator] Could not hook 'TMP_Text_SetCharArray_Hook3'. Likely due differences between different versions of the engine or text framework.
[Info   :XUnity.AutoTranslator] Loaded XUnity.AutoTranslator into Unity [2021.3.23f1] game.
[Info   :Il2CppInterop] Registered mono type XUnity.AutoTranslator.Plugin.Core.Il2CppManagedEnumerator in il2cpp domain
[Warning:XUnity.AutoTranslator] Input API is not available!
System.TypeLoadException: Could not load type 'UnityEngine.Input' from assembly 'UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInput()
   at XUnity.AutoTranslator.Plugin.Core.AutoTranslationPlugin.HandleInputSafe()
[Info   :XUnity.AutoTranslator] Skipping plugin scan because no plugin-specific translations has been registered.

**Comment by StarlightPN** [comment]
240710
BepinEx Bleeding Edge #692
XUnity.AutoTranslator 5.3.1
A25 Ver 1.7.0(2259)

에서 정상 동작 확인했습니다.
동일한 문제 발생 시, 별도 이슈로 오픈합니다.
![image](https://github.com/StarlightPN/A25-KoreanPatch/assets/168884301/001cbbda-bd90-4aca-af64-93d8897f25dd)
